[workspace]
resolver = "3"
members = ["mu", "mu_core", "mu_gui", "mu_gui2"]

[profile.release]
debug = true

[profile.dist]
inherits = "release"
opt-level = "z"
debug = false
lto = true   
strip = true
panic = "abort"
codegen-units = 1

[patch."https://github.com/zfphex/onmi"]
onmi = { path = "../projects/onmi/onmi" }