[package]
name = "gonk-types"
version = "0.1.0"
edition = "2021"

[dependencies]
symphonia = { git="https://github.com/pdeljanov/Symphonia"}
optick = "1.3.4"
serde = {version = "1.0.136", features = ["derive"]}