[package]
name = "gonk-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.27.0", features = ["bundled"] }
dirs = "4.0.0"
static_init = "1.0.2"
jwalk = "0.6.0"
dpc-pariter = "0.5.1"
toml = "0.5.8"
serde = { version = "1.0.136", features = ["derive"] }
tui = { version = "0.17.0", features = ["serde"] }
crossterm = "0.23.2"
optick = "1.3.4"
symphonia = { git="https://github.com/pdeljanov/Symphonia"}

[target.'cfg(windows)'.dependencies]
win-hotkey = { git = "https://github.com/zX3no/win-hotkey"}
