[package]
name = "gonk-core"
version = "0.2.0"
edition = "2021"
authors = ["Bay"]
description = "Database for gonk"
repository = "https://github.com/zX3no/gonk"
readme = "../README.md"
license = "CC0-1.0"

[dependencies]
memmap2 = "0.5.6"
rayon = "1.5.3"
walkdir = "2.3.2"
symphonia = { version = "0.5.1", default-features = false, features = [
    "flac",
    "mp3",
    "ogg",
    "vorbis",
] }

bench = { version = "0.1.0", path = "../../profiler/bench" }

[dev-dependencies]
tempfile = "*"
